@startuml
User -> Application : Launch App
Application -> UDIComponent: Init

UDIComponent -> ServiceDiscovery: get configuration urls(on country basis)
ServiceDiscovery ->UDIComponent : configuration urls, locale

UDIComponent ->UDIComponent : set locale

UDIComponent -> Janrain_OIDC: get Janrain OIDC configuration
Janrain_OIDC ->UDIComponent : success Janrain OIDC configuration
@enduml