@startuml
User -> Application : Launch App
Application -> UDIComponent: Init

UDIComponent -> ServiceDiscovery: get configuration urls(on country basis)
ServiceDiscovery ->UDIComponent : configuration urls, locale

UDIComponent ->UDIComponent : set locale

UDIComponent -> Janrain_OIDC: get Janrain OIDC configuration
Janrain_OIDC ->UDIComponent : success Janrain OIDC configuration

'User -> Application : Launch App(already initialized)


'UDIComponent -> ServiceDiscovery: get configuration urls(on country basis)
'ServiceDiscovery ->UDIComponent : return configuration urls

User -> UDIComponent : Login pressed
UDIComponent --> AppAuth:Authorization Request with Redirect URI

AppAuth  --> Browser : Authorization Request to launch browser
Browser --> Janrain_OIDC: Authorization Request with redirect url

CLP <-- Janrain_OIDC : Redirect to the CLP page for user authentication

CLP ->UDIComponent :Validate the credential with Janrain and and response request code.

UDIComponent ->Janrain_OIDC:request for token end point with auth code
Janrain_OIDC -> UDIComponent: success with access token and refresh token
@enduml