//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

namespace Philips.MRAutomation.Foundation.FrameworkCore.MRConfiguration
{
// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Configuration
{

    private List<object> itemsField = new List<object>();

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GenericConfiguration", typeof(ConfigurationGenericConfiguration), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("SimulatorConfiguration", typeof(ConfigurationSimulatorConfiguration), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("TimeoutConfiguration", typeof(ConfigurationTimeoutConfiguration), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("UserWarningMessages", typeof(ConfigurationUserWarningMessages), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<object> Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ConfigurationGenericConfiguration
{

    private string userWarningModeField;

    private string deletePatientFromDBField;

    private string performanceMonitoringField;

    private string packageIntegratorDataStore;

    private string connectivityDataStore;

    private string diskFileExportDataStore;

    private string dicomFILEOutputType_Enhanced;

    private string dicomDVDOutputType_Enhanced;

    private string dicomDVDOutputType_Classic;

    private string dicomFILEOutputType_Classic;

    private string testServer_MapDrive;

    private string productType;

    private string saveStateInformationField;

    private string useWindowWatcherField;

    private string bst_TestServer_Location;

    private string blr_TestServer_Location;    

    private string bst_TestServer_UID;

    private string bst_TestServer_PWD;

    private string blr_TestServer_UID;

    private string blr_TestServer_PWD;

    private string beforeExportFolderName;

    private string aandcRegressionDataStore;

    private string aandcPerformanceDataStore;

    private string interfaceFile;

    private string iSiteClassicNode;

    private string iSiteEnhancedNode;

    private string ewsClassicNode;

    private string ewsEnhancedNode;

    private string usbDrivePath;

    private string copyTestCaseLog;

    private string copyReportToServer;

    private string mrApplicationLogPath;

    private string copyTestSuiteLog;
	
	private string scanAutomationHostName;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserWarningMode
    {
        get
        {
            return this.userWarningModeField;
        }
        set
        {
            this.userWarningModeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DeletePatientFromDB
    {
        get
        {
            return this.deletePatientFromDBField;
        }
        set
        {
            this.deletePatientFromDBField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PerformanceMonitoring
    {
        get
        {
            return this.performanceMonitoringField;
        }
        set
        {
            this.performanceMonitoringField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PackageIntegratorDataStore
    {
        get
        {
            return this.packageIntegratorDataStore;
        }
        set
        {
            this.packageIntegratorDataStore = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ConnectivityDataStore
    {
        get
        {
            return this.connectivityDataStore;
        }
        set
        {
            this.connectivityDataStore = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DiskFileExportDataStore
    {
        get
        {
            return this.diskFileExportDataStore;
        }
        set
        {
            this.diskFileExportDataStore = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SaveStateInformation
    {
        get
        {
            return this.saveStateInformationField;
        }
        set
        {
            this.saveStateInformationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UseWindowWatcher
    {
        get
        {
            return this.useWindowWatcherField;
        }
        set
        {
            this.useWindowWatcherField = value;
        }

    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DICOMFILEOutputType_Enhanced
    {
        get
        {
            return this.dicomFILEOutputType_Enhanced;
        }
        set
        {
            this.dicomFILEOutputType_Enhanced = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DICOMDVDOutputType_Enhanced
    {
        get
        {
            return this.dicomDVDOutputType_Enhanced;
        }
        set
        {
            this.dicomDVDOutputType_Enhanced = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DICOMDVDOutputType_Classic
    {
        get
        {
            return this.dicomDVDOutputType_Classic;
        }
        set
        {
            this.dicomDVDOutputType_Classic = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DICOMFILEOutputType_Classic
    {
        get
        {
            return this.dicomFILEOutputType_Classic;
        }
        set
        {
            this.dicomFILEOutputType_Classic = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TestServer_MapDrive
    {
        get
        {
            return this.testServer_MapDrive;
        }
        set
        {
            this.testServer_MapDrive = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductType
    {
        get
        {
            return this.productType;
        }
        set
        {
            this.productType = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BST_TestServer_Location
    {
        get
        {
            return this.bst_TestServer_Location;
        }
        set
        {
            this.bst_TestServer_Location = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BLR_TestServer_Location
    {
        get
        {
            return this.blr_TestServer_Location;
        }
        set
        {
            this.blr_TestServer_Location = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BST_TestServer_UID
    {
        get
        {
            return this.bst_TestServer_UID;
        }
        set
        {
            this.bst_TestServer_UID = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BST_TestServer_PWD
    {
        get
        {
            return this.bst_TestServer_PWD;
        }
        set
        {
            this.bst_TestServer_PWD = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BLR_TestServer_UID
    {
        get
        {
            return this.blr_TestServer_UID;
        }
        set
        {
            this.blr_TestServer_UID = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BLR_TestServer_PWD
    {
        get
        {
            return this.blr_TestServer_PWD;
        }
        set
        {
            this.blr_TestServer_PWD = value;
        }
    }
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BeforeExportFolderName
    {
        get
        {
            return this.beforeExportFolderName;
        }
        set
        {
            this.beforeExportFolderName = value;
        }
    }
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AandCRegressionDataStore
    {
        get
        {
            return this.aandcRegressionDataStore;
        }
        set
        {
            this.aandcRegressionDataStore = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AandCPerformanceDataStore
    {
        get
        {
            return this.aandcPerformanceDataStore;
        }
        set
        {
            this.aandcPerformanceDataStore = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InterfaceFile
    {
        get
        {
            return this.interfaceFile;
        }
        set
        {
            this.interfaceFile = value;
        }
    }
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ISiteClassicNode//ISiteClassicNode
    {
        get
        {
            return this.iSiteClassicNode;
        }
        set
        {
            this.iSiteClassicNode = value;
        }
    }
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ISiteEnhancedNode
    {
        get
        {
            return this.iSiteEnhancedNode;
        }
        set
        {
            this.iSiteEnhancedNode = value;
        }
    }
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EWSClassicNode
    {
        get
        {
            return this.ewsClassicNode;
        }
        set
        {
            this.ewsClassicNode = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EWSEnhancedNode
    {
        get
        {
            return this.ewsEnhancedNode;
        }
        set
        {
            this.ewsEnhancedNode = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string USBDrivePath
    {
        get
        {
            return this.usbDrivePath;
        }
        set
        {
            this.usbDrivePath = value;
        }
    }
     /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CopyTestCaseLog
    {
        get
        {
            return this.copyTestCaseLog;
        }
        set
        {
            this.copyTestCaseLog = value;
        }
    }
      /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CopyReportToServer
    {
        get
        {
            return this.copyReportToServer;
        }
        set
        {
            this.copyReportToServer = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MRApplicationLogPath
    {
        get
        {
            return this.mrApplicationLogPath;
        }
        set
        {
            this.mrApplicationLogPath = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CopyTestSuiteLog
    {
        get
        {
            return this.copyTestSuiteLog;
        }
        set
        {
            this.copyTestSuiteLog = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ScanAutomationHostName {
        get {
            return this.scanAutomationHostName;
        }
        set {
            this.scanAutomationHostName = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ConfigurationSimulatorConfiguration
{

    private ConfigurationSimulatorConfigurationWorkstation[] workstationField;

    private ConfigurationSimulatorConfigurationReconWorkstation[] reconWorkstationField;

    private ConfigurationSimulatorConfigurationSimulator[] simulatorField;
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WORKSTATION", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationSimulatorConfigurationWorkstation[] WORKSTATION
    {
        get
        {
            return this.workstationField;
        }
        set
        {
            this.workstationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RECON_WORKSTATION", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationSimulatorConfigurationReconWorkstation[] RECON_WORKSTATION
    {
        get
        {
            return this.reconWorkstationField;
        }
        set
        {
            this.reconWorkstationField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SIMULATOR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationSimulatorConfigurationSimulator[] SIMULATOR
    {
        get
        {
            return this.simulatorField;
        }
        set
        {
            this.simulatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ConfigurationSimulatorConfigurationWorkstation
{

    private string startScannerSimulatorFileNameField;

    private string startCoilSimulatorFileNameField;

    private string stopScannerSimulatorFileNameField;

    private string stopReconSimulatorFileNameField;

    private string stopCoilSimulatorFileNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StartScannerSimulatorFileName
    {
        get
        {
            return this.startScannerSimulatorFileNameField;
        }
        set
        {
            this.startScannerSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StartCoilSimulatorFileName
    {
        get
        {
            return this.startCoilSimulatorFileNameField;
        }
        set
        {
            this.startCoilSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopScannerSimulatorFileName
    {
        get
        {
            return this.stopScannerSimulatorFileNameField;
        }
        set
        {
            this.stopScannerSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopReconSimulatorFileName
    {
        get
        {
            return this.stopReconSimulatorFileNameField;
        }
        set
        {
            this.stopReconSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopCoilSimulatorFileName
    {
        get
        {
            return this.stopCoilSimulatorFileNameField;
        }
        set
        {
            this.stopCoilSimulatorFileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ConfigurationSimulatorConfigurationReconWorkstation
{

    private string startScannerSimulatorFileNameField;

    private string startCoilSimulatorFileNameField;

    private string stopScannerSimulatorFileNameField;

    private string stopReconSimulatorFileNameField;

    private string stopCoilSimulatorFileNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StartScannerSimulatorFileName
    {
        get
        {
            return this.startScannerSimulatorFileNameField;
        }
        set
        {
            this.startScannerSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StartCoilSimulatorFileName
    {
        get
        {
            return this.startCoilSimulatorFileNameField;
        }
        set
        {
            this.startCoilSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopScannerSimulatorFileName
    {
        get
        {
            return this.stopScannerSimulatorFileNameField;
        }
        set
        {
            this.stopScannerSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopReconSimulatorFileName
    {
        get
        {
            return this.stopReconSimulatorFileNameField;
        }
        set
        {
            this.stopReconSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopCoilSimulatorFileName
    {
        get
        {
            return this.stopCoilSimulatorFileNameField;
        }
        set
        {
            this.stopCoilSimulatorFileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ConfigurationSimulatorConfigurationSimulator
{

    private string startScannerSimulatorFileNameField;

    private string startCoilSimulatorFileNameField;

    private string stopScannerSimulatorFileNameField;

    private string stopReconSimulatorFileNameField;

    private string stopCoilSimulatorFileNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StartScannerSimulatorFileName
    {
        get
        {
            return this.startScannerSimulatorFileNameField;
        }
        set
        {
            this.startScannerSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StartCoilSimulatorFileName
    {
        get
        {
            return this.startCoilSimulatorFileNameField;
        }
        set
        {
            this.startCoilSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopScannerSimulatorFileName
    {
        get
        {
            return this.stopScannerSimulatorFileNameField;
        }
        set
        {
            this.stopScannerSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopReconSimulatorFileName
    {
        get
        {
            return this.stopReconSimulatorFileNameField;
        }
        set
        {
            this.stopReconSimulatorFileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StopCoilSimulatorFileName
    {
        get
        {
            return this.stopCoilSimulatorFileNameField;
        }
        set
        {
            this.stopCoilSimulatorFileNameField = value;
        }
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConfigurationTimeoutConfiguration {
    
    private string cONNECTIVITYField;
    
    private string fIXEDINTEGRATORField;
    
    private string vARIABLEINTEGRATORField;
    
    private string pACKAGEINTEGRATORField;
    
    private string rELIABILITYField;

    private string iNTEGRATORField;

    private string eXAMCARDRELIABILITY;

    private string cTPField;

    private string vIEWINGREGRESSIONField;

    private string eCREGRESSIONField;

    private string lAUNCHPADREGRESSIONField;

    private string vIEWINGRELIABILITYField;

    private string aandCREGRESSIONField;

    private string hARDWAREAUTOMATIONField;

    private string performanceFiled;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CONNECTIVITY {
        get {
            return this.cONNECTIVITYField;
        }
        set {
            this.cONNECTIVITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FIXEDINTEGRATOR {
        get {
            return this.fIXEDINTEGRATORField;
        }
        set {
            this.fIXEDINTEGRATORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VARIABLEINTEGRATOR {
        get {
            return this.vARIABLEINTEGRATORField;
        }
        set {
            this.vARIABLEINTEGRATORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PACKAGEINTEGRATOR {
        get {
            return this.pACKAGEINTEGRATORField;
        }
        set {
            this.pACKAGEINTEGRATORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RELIABILITY {
        get {
            return this.rELIABILITYField;
        }
        set {
            this.rELIABILITYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string INTEGRATOR
    {
        get
        {
            return this.iNTEGRATORField;
        }
        set
        {
            this.iNTEGRATORField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EXAMCARDRELIABILITY
    {
        get
        {
            return this.eXAMCARDRELIABILITY;
        }
        set
        {
            this.eXAMCARDRELIABILITY = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CTP
    {
        get
        {
            return this.cTPField;
        }
        set
        {
            this.cTPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VIEWINGREGRESSION
    {
        get
        {
            return this.vIEWINGREGRESSIONField;
        }
        set
        {
            this.vIEWINGREGRESSIONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LAUNCHPADREGRESSION
    {
        get
        {
            return this.lAUNCHPADREGRESSIONField;
        }
        set
        {
            this.lAUNCHPADREGRESSIONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ECREGRESSION
    {
        get
        {
            return this.eCREGRESSIONField;
        }
        set
        {
            this.eCREGRESSIONField = value;
        }
    }

        /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VIEWINGRELIABILITY
    {
        get
        {
            return this.vIEWINGRELIABILITYField;
        }
        set
        {
            this.vIEWINGRELIABILITYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AandCREGRESSION
    {
        get
        {
            return this.aandCREGRESSIONField;
        }
        set
        {
            this.aandCREGRESSIONField = value;
        }
    }

        /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HARDWAREAUTOMATION
    {
        get
        {
            return this.hARDWAREAUTOMATIONField;
        }
        set
        {
            this.hARDWAREAUTOMATIONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PERFORMANCE
    {
        get
        {
            return this.performanceFiled;
        }
        set
        {
            this.performanceFiled = value;
        }
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ConfigurationUserWarningMessages
{
    private List<ConfigurationUserWarningMessagesTestcase> testcaseField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Testcase", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<ConfigurationUserWarningMessagesTestcase> Testcase
    {
        get
        {
            return this.testcaseField;
        }
        set
        {
            this.testcaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ConfigurationUserWarningMessagesTestcase
{

    private string assemblyField;

    private string classNameField;

    private string titleField;

    private string messageField;

    private string buttonsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Assembly
    {
        get
        {
            return this.assemblyField;
        }
        set
        {
            this.assemblyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClassName
    {
        get
        {
            return this.classNameField;
        }
        set
        {
            this.classNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Buttons
    {
        get
        {
            return this.buttonsField;
        }
        set
        {
            this.buttonsField = value;
        }
    }
}
}
