/*
 * Copyright (c) Koninklijke Philips N.V., 2015.
 * All rights reserved.
 */

package com.philips.pins.shinelib.datatypes;

/**
 * Created by 310188215 on 07/05/15.
 */
public enum SHNDataType {
    Unknown,
    DebugMoonshine,
    HeartRate,
    EnergyExpenditure,
    EnergyIntake,
    Steps,
    TestResultMoonshine,
    HeartRateResting,
    HeartRateRecovery,
    Sleep,
    BodyTemperature,
    ActivityTypeCM3Deprecated,
    ActivityTypeMoonshine,
    ActiveEnergyExpenditureMoonshine,
    BodyWeight,
    BloodPressure,
    BodyComposition,
    Weight,
    SubjectiveDataMoonshine,
    ResetSourceMoonshine,
    EventMoonshine,
    DebugStringMoonshine,
    HeartBeatsMoonshine,
    ActivityCountPerMinute,
    ActivityCountDebugMoonshine,
    StepsDebugMoonshine,
    EnergyExpenditureDebug,
    CardioFitnessIndex,
    Vo2Max,
    VisibleLight,
    UVLight,
    RespirationRate,
    RespirationRateDebugMoonshine,
    UserConfigChangedEventHeightMoonshine,
    UserConfigChangedEventWeightMoonshine,
    UserConfigChangedEventSexMoonshine,
    UserConfigChangedEventBirthdayMoonshine,
    UserConfigChangedEventBMRMoonshine,
    UserConfigChangedEventHeartRateZonesMoonshine,
    UserConfigChangedEventHandednessMoonshine,
    UserConfigChangedEventWearingPositionMoonshine,
    UserConfigChangedEventLanguageMoonshine,
    UserConfigChangedEventRestingHeartRateMoonshine,
    ActivitySessionMoonshine,
    DayTotalsMoonshine,
    BatteryState,
    UserConfigChangedEventTargetsMoonshine,
    ActivityDayTotalsMoonshine,
    UserConfigChangedEventSedentaryPeriodMoonshine,
    UserConfigChangedEventSedentaryNotificationMoonshine,
    CM3AccelerometerDataMoonshine,
    CM3HeartRateMoonshine,
    UserConfigChangedEventEnergyIntakeMoonshine,
    ChangeTimeMoonshine,
    FatPercentage,
    Raw,
    WeSTDataMoonshine,
    DailyCumulativeTotalEnergyExpenditure,
    ActiveEnergyExpenditureDebugMoonshine,
    ActiveMinutes,
    BloodOxygenLevel,
    CM3RestingHeartRateDataMoonshine,
    EnergyIntakeMoonshine
}
