/*
 * Copyright (c) Koninklijke Philips N.V., 2015.
 * All rights reserved.
 */

package com.philips.pins.shinelib.datatypes;

/**
 * Created by 310188215 on 07/05/15.
 */
public enum SHNDataType {
    Unknown,
    Debug,
    HeartRate,
    EnergyExpenditure,
    EnergyIntake,
    Steps,
    TestResultMoonshine,
    HeartRateResting,
    HeartRateRecovery,
    Sleep,
    BodyTemperature,
    ActivityTypeCM3Deprecated,
    ActivityType,
    ActiveEnergyExpenditure,
    BodyWeight,
    BloodPressure,
    BodyComposition,
    Weight,
    SubjectiveDataMoonshine,
    ResetSourceMoonshine,
    EventMoonshine,
    DebugStringMoonshine,
    HeartBeatsMoonshine,
    ActivityCounts,
    ActivityCountsDebug,
    StepsDebug,
    EnergyExpenditureDebug,
    CardioFitnessIndex,
    Vo2Max,
    VisibleLight,
    UVLight,
    RespirationRate,
    RespirationRateDebug,
    UserConfigChangedEventHeight,
    UserConfigChangedEventWeight,
    UserConfigChangedEventSex,
    UserConfigChangedEventBirthday,
    UserConfigChangedEventBMR,
    UserConfigChangedEventHRZones,
    UserConfigChangedEventHandedness,
    UserConfigChangedEventSensingPosition,
    UserConfigChangedEventLanguage,
    UserConfigChangedEventRestingHeartRate,
    ActivitySession,
    DayTotals,
    Battery,
    UserConfigChangedEventTargets,
    ActivityDayTotals,
    UserConfigChangedEventSedentaryPeriod,
    UserConfigChangedEventSedentaryNotification,
    AccelerometerData,
    CM3HeartRate,
    CM3RestingHeartRateDataMoonshine,
    UserConfigChangedEventEnergyIntake,
    ChangeTime,
    FatPercentage,
    Raw,
    WeSTDataBlob,
    TotalEnergyExpenditure,
    ActiveEnergyExpenditureDebug,
    ActiveMinutes,
    BloodOxygenLevel
}
