start xcopy "..\Src\Reference\Microsoft.VisualStudio.QualityTools.Sqm.dll" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\Microsoft.VisualStudio.TestTools.UITest.Common.dll" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\Microsoft.VisualStudio.TestTools.UITest.Extension.dll" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\Microsoft.VisualStudio.TestTools.UITest.Extension.IE.Communication.Interop.dll" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\Microsoft.VisualStudio.TestTools.UITest.Extension.IE.dll" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\Microsoft.VisualStudio.TestTools.UITest.Extension.Uia.dll" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\Microsoft.VisualStudio.TestTools.UITest.Playback.Engine.dll" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\CrashNotifierConfig.xml" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\RunSequence.xml" "..\Bin\" /Y /I /O
start xcopy "..\Src\Reference\TestPicker.xml" "..\Bin\" /Y /I /O