package com.philips.cl.di.common.ssdp.contants;

/**
 */
public enum MessageID {
	AT_BITMAP_AVAILABLE, AT_NEXT_PLAY_ERROR,
	// TWONKY SERVICE

	AT_NEXT_PLAYED, AT_NO_BITMAP, AT_PAUSE_ERROR, AT_PAUSED,
	// TWONKY LOCAL SERVER

	AT_PLAY_ERROR, AT_PLAYED, AT_PREVIOUS_PLAY_ERROR, AT_PREVIOUS_PLAYED, AT_RESUME_ERROR, AT_RESUMED, BM_BACKGROUND, BM_FOREGROUND, CPS_DIRECTORY_CLICKED, CPS_EMPTY_LIST,
	// TWONKY LOCAL SERVER ERROR

	CPS_ERROR, CPS_ITEM_CLICKED, CPS_LIST_CREATED, CPS_MULTIMEDIA_ITEM_CLICKED, CPS_UNSUPPORTED_ITEM_CLICKED,
	// TWONKY SERVER ERROR

	DEVICE_DISCOVERED, DEVICE_LOST, DM_DEVICE_ADDED, DM_DEVICE_LOST, DM_DEVICE_REMOVED,
	// GENERIC MESSAGES

	ERROR, HM_CALL,
	// ERROR

	HM_SMS,
	// JointSpace SERVICE

	JSS_SERVICE_START_FAILED,
	// JSS_SERVICE_STOP_FAILED,

	JSS_SERVICE_STARTED, JSS_SERVICE_STOPPED,
	// DeviceManager SERVICE
	// messages sent with device ID

	LCM_CONTENT_UPDATED, LCM_THUMBNAIL_FETCHED, LOCAL_SERVER_ERR_SD_CARD_ERROR,
	// PowerManager SCREEN

	LOCAL_SERVER_ERR_START_CANCELED, LOCAL_SERVER_ERR_START_FAILED,
	// BackgroundModeManager

	LOCAL_SERVER_ERR_UNKNOWN, LOCAL_SERVER_ERR_WIFI_ERROR,
	// NetworkManager WIFI

	LOCAL_SERVER_SD_CARD_ERROR, LOCAL_SERVER_START_CANCELED, LOCAL_SERVER_START_FAILED,
	// PhoneManager SMS/CALL

	LOCAL_SERVER_STARTED, LOCAL_SERVER_STOPPED,
	// ContentProviderService

	LOCAL_SERVER_UNKNOWN, LOCAL_SERVER_WIFI_ERROR, LPS_LOCK_BG_MODE, LPS_UNLOCK_BG_MODE,
	// NotificationID
	NID_COMMAND_FOR_LONG_TASK_DONE, NID_COMMAND_FOR_LONG_TASK_SENT, NM_NETWORK_CHANGED,
	// ServiceManager

	NM_WIFI_DISABLED, NM_WIFI_ENABLED, PCS_COMMAND_ISSUED, PCS_META_DATA_CHANGED, PCS_ON_PLAY_STATE_CHANGED, PCS_PLAY_POSITION_CHANGED, PCS_QUEUING_FINISHED, PCS_QUEUING_STATE_CHANGED, // PlaybackControllerService
	PCS_RENDERER_ERROR, PCS_TRACK_CHANGED, PCS_VOLUME_CHANGED, PM_SCREEN_OFF, PM_SCREEN_ON, SM_SERVICE_DISABLE_UPNP_DEVICES, SM_SERVICES_STARTED, SM_SERVICES_STOPPED,
	// PlaybackController AsyncTask result

	SM_START_SERVICES, SM_STOP_SERVICES, TS_CHANGE_LOCAL_SERVER_NAME, TS_IS_LOCAL_SERVER_RUNNING, TS_LOCAL_SERVER_ERROR, TS_LOCAL_SERVER_SCANNING_COMPLETED, TS_LOCAL_SERVER_SCANNING_STARTED, TS_RESTART_LOCAL_SERVER, TS_SERVICE_START_FAILED, TS_SERVICE_STARTED, TS_SERVICE_STOP_FAILED, TS_SERVICE_STOPPED,
	// Local content manager

	TS_START_LOCAL_SERVER, TS_STOP_LOCAL_SERVER,
	// Local playback service

	// View Controllers
	VC_RECONNECT_FAILED, VC_SHOW_REFRESH;

	/**
	 * Method getID.
	 * 
	 * @param ordinal
	 *            int
	 * @return MessageID
	 */
	public static MessageID getID(final int ordinal) {
		return (MessageID.values())[ordinal];
	}
}
