name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  https_proxy=http://iet_mobileplatform@philips.com:#W3llc4m3@proxy.local
  http_proxy=http://iet_mobileplatform@philips.com:#W3llc4m3@proxy.local
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
